### ISSUE TITLE
2D-VMD using Python

### ISSUE THREAD

**Issue by 5586608dh** [DodgeHo/VMD_2D_cpp#1]
Hello boss, have you implemented 2D-VMD using Python

**Comment by DodgeHo** [comment]
Actually, I didn't.
I thought it must be easy. If you have gone through Github and found nothing, I'll to see what I can do.

**Comment by 5586608dh** [comment]
I am not capable of using Python to implement 2D-VMD. If you have the ability and the time to implement it, I would greatly appreciate it

**Comment by DodgeHo** [comment]
I suppose I can give it a shot. 
However, you must be aware of VMD(1d) consists of FFT and other matrix calculation. What do you have in mind as the tool library in Python for 2D FFT and so? I was thinking about the usage of OpenCV, since you know, gray images are one kind of the 2D signal we could analyze. 
If you have better idea, please let me know. I will write you back in a few days.

**Comment by 5586608dh** [comment]
Sorry, my abilities are limited. My main focus is on researching digital watermarking, which involves embedding watermark information into images and meeting certain criteria. I would like to use 2D-VMD as a method for processing images, decompose them through VMD, and embed a watermark into one IMF component. Finally, I will merge all IMFs to achieve the goal of embedding the watermark

**Comment by DodgeHo** [comment]
I notice you said you want to process image. Is it gray images or color images? Because a RGB picture is a 3D matrix and the third dimension only have 3 elements. If you are handling color images, maybe VMD is not the suitable way.

**Comment by 5586608dh** [comment]
Thank you for your concern. I am processing grayscale images, so I would like to try the effect of VMD

**Comment by DodgeHo** [comment]
I have implemented 2D VMD in Python. Please visit https://github.com/DodgeHo/VMD_2D_python. I will close this issue.
